nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

supportedArchitectures:
  libc:
    - current
    - libc
    - musl
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-3.6.1.cjs
